### ISSUE TITLE
symcl?

### ISSUE THREAD

**Issue by commander-trashdin** [numcl/numcl#10]
I was explaining some stuff to some new lisp guys about linear recurrences and ~ while also implementing it for fun, and the next second I found myself writing a small symbolics library. So far I've only done some pretty fast linear recurrences calculations (such as nth, sums, hadamar products) and also some operations on (integer) polynomials.

I'm lazy, so this is in a very dirty state -- no comments, not-the-best-naming, etc. (this is why I don't provide a link, I'm ashamed)
But if you think this is something that can go alongside numcl, I'll be glad to refactor it and show.

**Comment by guicho271828** [comment]
Thank you for your interest! Since I have no clue, I would check what the linear recurrence is all about... for now, I am planning an initial release (which is slow and does not include the optimized versions you can find in the branches -- see #4 ).

Note that I am going to make numcl extensible so that it can have several JIT compiler back-ends, including native lisp compiler, native C (dynamically generated binding unlike python), opencl, cuda and so forth. If you happen to write one it is also greatly appreciated.

**Comment by commander-trashdin** [comment]
No, haven't done that.
I'll go on making my thing. I wrote some matrix multiplication/exponentiation (for O(logn)) for it.
But I'm pretty confident that this you have.
I'll also need polynomial operations (+, *, `floor). Do you have these too? (or maybe planning)


The only thing I can add (off topic) is that you probably want to have a look at `(require :sb-gmp)`.

**Comment by guicho271828** [comment]
thanks, Ill take a look > `sb-gmp`

**Comment by guicho271828** [comment]
> polynomical operations

most numeric functions in CL package are supported in numcl. Definitions starting from here: https://github.com/numcl/numcl/blob/master/src/5numeric.lisp#L216

**Comment by commander-trashdin** [comment]
Oh no, I was asking about stuff like
Defining some struc/type, that lets me represent a 'x^3-4x+2` and addition/multiplication for those.

**Comment by guicho271828** [comment]
oh, so not only for the numbers. I see.

**Comment by guicho271828** [comment]
In the latest push to the `main` branch, `einsum` accepts an extended notation that allows to perform an arbitrary operation in the innermost loop. If you need to run `y ← x^3-4x+2` in the inner loop, you would write

 `(einsum '(i -> (+ 2 (* -4 $1) (expt $1 3)) -> i) x)`

 where x is an array.
 If you want to support some form of user-defined generic plus (say: `generic:+`), you can then write

 `(einsum '(i -> (generic:+ 2 (generic:* -4 $1) (generic:expt $1 3)) -> i) x)`.

**Comment by commander-trashdin** [comment]
I see. 
This is probably not the best place for a long discussion. When you done with a release (->little bit less busy), can you email me? I'd like to ask a couple of things since whatever I do, I probably want to base it on numcl.
