### ISSUE TITLE
cannot run (matmul ....)

### ISSUE THREAD

**Issue by PiotrWasik** [numcl/numcl#14]
Hey,

Thanks for the effort, your project will be exactly what I need, a pure lisp numerical library :-)

I installed it today and I got this however:

an attempt to evaluate
(in-package :numcl) 
(matmul '#2A((0.0 1.0) (2.0 3.0)) '#2A((5.0 6.0) (7.0 8.0))) 

causes an error pasted below and also available here: https://pastebin.com/Pjk4aK2R

I tried various versions of SBCL, including 1.5.1 and 1.5.6
Fresh quicklisp as of 2019/09/14
libraries downloaded from git directly as master on 2019/09/14 linked as local-projects in quicklisp (so taking precedence over quicklisp):
numcl
specialized-function
trivia
type-i
type-r

Pattern: (((T NUMCL.IMPL::_) T) ((NUMCL.IMPL::_ T) T)
          ((NIL NUMCL.IMPL::_) NIL) ((NUMCL.IMPL::_ NIL) NIL)
          (((TYPE-R:COMPLEX-TYPE NUMCL.IMPL::PREV)
            (TYPE-R:COMPLEX-TYPE NUMCL.IMPL::NOW))
           `(COMPLEX
             ,#1=(NUMCL.IMPL::FN NUMCL.IMPL::PREV
                  NUMCL.IMPL::NOW)))
          (((TYPE-R:COMPLEX-TYPE NUMCL.IMPL::PREV)
            NUMCL.IMPL::_)
           `(COMPLEX ,#1#))
          ((NUMCL.IMPL::_ (TYPE-R:COMPLEX-TYPE NUMCL.IMPL::NOW))
           `(COMPLEX ,#1#))
          (((TYPE-R:OR-TYPE NUMCL.IMPL::TYPES1)
            (TYPE-R:OR-TYPE NUMCL.IMPL::TYPES2))
           (NUMCL.IMPL::SIMPLIFY-OR-TYPES
            (ALEXANDRIA.1.0.0:MAP-PRODUCT #'NUMCL.IMPL::FN
                                          NUMCL.IMPL::TYPES1
                                          NUMCL.IMPL::TYPES2)))
          (((TYPE-R:OR-TYPE NUMCL.IMPL::TYPES1) NUMCL.IMPL::_)
           (NUMCL.IMPL::SIMPLIFY-OR-TYPES
            (MAPCAR
             (LAMBDA (TYPE)
               (NUMCL.IMPL::FN TYPE NUMCL.IMPL::NOW))
             NUMCL.IMPL::TYPES1)))
          ((NUMCL.IMPL::_ (TYPE-R:OR-TYPE NUMCL.IMPL::TYPES2))
           (NUMCL.IMPL::SIMPLIFY-OR-TYPES
            (MAPCAR
             (LAMBDA (TYPE)
               (NUMCL.IMPL::FN NUMCL.IMPL::PREV TYPE))
             NUMCL.IMPL::TYPES2)))
          (((TYPE-R:REAL-SUBTYPE NUMCL.IMPL::L1 NUMCL.IMPL::H1)
            (TYPE-R:REAL-SUBTYPE NUMCL.IMPL::L2 NUMCL.IMPL::H2))
           (NUMCL.IMPL::LET ((TYPE
                              (NUMCL.IMPL::FLOAT-CONTAGION
                               NUMCL.IMPL::PREV NUMCL.IMPL::NOW
                               :INT-INT-RESULT
                               NUMCL.IMPL::INT-INT-RESULT)))
             (FLET ((NUMCL.IMPL::C (NUMCL.IMPL::VALUE)
                      (NUMCL.IMPL::%INTERVAL-COERCE
                       NUMCL.IMPL::VALUE TYPE)))
               (TRIVIA.LEVEL2:EMATCH (FUNCALL
                                      NUMCL.IMPL::INTERVAL-OP
                                      NUMCL.IMPL::L1
                                      NUMCL.IMPL::H1
                                      NUMCL.IMPL::L2
                                      NUMCL.IMPL::H2)
                 ((LIST NUMCL.IMPL::LOW NUMCL.IMPL::HIGH)
                  (IF (OR (EQ NUMCL.IMPL::LOW 'COMMON-LISP:*)
                          (EQ NUMCL.IMPL::HIGH 'COMMON-LISP:*)
                          (COMMON-LISP:<= NUMCL.IMPL::LOW
                                          NUMCL.IMPL::HIGH))
                      (IF (EQ TYPE 'INTEGER)
                          (PROGN
                           (CHECK-TYPE NUMCL.IMPL::LOW
                                       (OR INTEGER
                                           (EQL COMMON-LISP:*)))
                           (CHECK-TYPE NUMCL.IMPL::HIGH
                                       (OR INTEGER
                                           (EQL COMMON-LISP:*)))
                           `(INTEGER
                             ,@(NUMCL.IMPL::INTERVAL-INTERSECTION
                                NUMCL.IMPL::LOW NUMCL.IMPL::HIGH
                                MOST-NEGATIVE-FIXNUM
                                MOST-POSITIVE-FIXNUM)))
                          `(,TYPE
                            ,(NUMCL.IMPL::C NUMCL.IMPL::LOW)
                            ,(NUMCL.IMPL::C NUMCL.IMPL::HIGH)))
                      NIL))))))) 
 Values: (COMMON-LISP:* COMMON-LISP:*)
   [Condition of type TRIVIA.LEVEL2:MATCH-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1023F39DE3}>)

Backtrace:
  0: ((LABELS NUMCL.IMPL::FN :IN NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT) COMMON-LISP:* COMMON-LISP:*)
  1: ((FLET "FN419" :IN NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT) COMMON-LISP:*)
  2: ((FLET "FN383" :IN NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT) COMMON-LISP:*)
  3: ((LABELS NUMCL.IMPL::FN :IN NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT) COMPLEX COMPLEX)
  4: (REDUCE #<CLOSURE (LABELS NUMCL.IMPL::FN :IN NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT) {1013BFFBFB}> (COMPLEX COMPLEX))
  5: (NUMCL.IMPL::INFER-RATIONAL-ARITHMETIC-RESULT #<FUNCTION NUMCL.IMPL::INTERVAL-MUL> (COMPLEX COMPLEX) INTEGER)
  6: (NUMCL.IMPL::MUL-TO-FLOAT-TYPE COMPLEX COMPLEX)
  7: (NUMCL.IMPL::INFER-TYPE COMMON-LISP:* COMPLEX COMPLEX)
  8: (NUMCL.IMPL::INTERPRET-TYPE (COMMON-LISP:* T T))
  9: (NUMCL.IMPL::INTERPRET-TYPE (COMMON-LISP:+ (INTEGER 0 0) (COMMON-LISP:* T T)))
 10: (NUMCL.IMPL::EINSUM-OUTPUT-TYPES ((COMMON-LISP:+ NUMCL.IMPL::@1 (COMMON-LISP:* NUMCL.IMPL::$1 NUMCL.IMPL::$2))) (NUMCL.IMPL::$1 NUMCL.IMPL::$2) (NUMCL.IMPL::@1) #2A((0.0 1.0) (2.0 3.0)) #2A((5.0 6.0) ..
 11: (MATMUL #2A((0.0 1.0) (2.0 3.0)) #2A((5.0 6.0) (7.0 8.0)) NIL)
 12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (MATMUL #2A((0.0 1.0) (2.0 3.0)) #2A((5.0 6.0) (7.0 8.0))) #<NULL-LEXENV>)
 **13: (EVAL (MATMUL #2A((0.0 1.0) (2.0 3.0)) #2A((5.0 6.0) (7.0 8.0))))**
 --more--

Cheers,
Piotr (puchacz)

**Comment by guicho271828** [comment]
Short answer: *You have to wrap your array with `asarray` function.*

Long Answer: In order to guarantee the speed and to simplify the implementation, the arrays given to numcl functions must satisfy the following two conditions:

* It is a *specialized array*. Things of type `(array single-float)`, `(array (unsigned-byte 16))` etc.
* It is an array *displaced to a simple 1D specialized array*. "Simple" means a non-displaced, non-adjustable array without fill pointer.

In your case, `#2A((0.0 ...) ...)` is a simple array of type `(array T)`. It is not displaced because it is simple. There are two ways to create an array similar to what you have and is compatible to numcl:

* `(reshape (arange 4.0) '(2 2))`
* `(asarray #2A((0.0 1.0) (2.0 3.0)))` or `(asarray '((0.0 1.0) (2.0 3.0)))` or `(asarray '(#(0.0 1.0) #(2.0 3.0))`. They all works, see the doc for `asarray`.

**Comment by guicho271828** [comment]
I updated the readme to reflect this fact... I also consider making the error message more helpful. Thank you

**Comment by PiotrWasik** [comment]
Thanks, it works :-)

Just sometimes I have to specify type explicitly, eg.:

(type-of (numcl:asarray #2a((0.0 1.0) (2.0 3.0)) :type 'double-float))
--> (ARRAY DOUBLE-FLOAT (2 2)) ;; OK
(type-of (numcl:asarray #2a((0.0 1.0) (2.0 3.0)))) --> (ARRAY T (2 2)) ;;
not OK
but
(type-of (numcl:asarray '((0.0 1.0) (2.0 3.0)))) --> (ARRAY DOUBLE-FLOAT (2
2)) ;; OK again

Not an issue for me however.

By the way, I changed all places I found for float type to default it to
double-float:

(setf *read-default-float-format* 'double-float)

and

(defconstant *numcl-default-float-format* 'double-float
  "The default format for numcl arrays. Bignums and ratios are coerced into
this type
during computation.")

Why did you settle on single-float please?

I know it is annoying in Common Lisp that functions like (log 2) return
single-float if input is integer.

Cheers,
Piotr

niedz., 15 wrz 2019 o 14:24 Masataro Asai <notifications@github.com>
napisał(a):

**Comment by guicho271828** [comment]
I will try to address that behavior but pull request is always welcomed :)

I opted for single floats because  machine learning is the main target.

i wish to make the default format a defparameter, not a constant, but currently I do not have a good  idea to propagate it in the compile time.  any suggestions?

**Comment by PiotrWasik** [comment]
I did not realise there was performance penalty for using double-floats. Is
there? Maybe I should stick to single-floats as well.

Unfortunately no suggestions, I am not good with this side of Lisp
unfortunately. I know you use macros so just to be safe I changed these
variables in your source files, removed all fasls and restarted SBCL.... A
sign of understanding these mechanisms poorly ;-) When I learn more, sure
there will be time for pull requests!

Cheers,
Piotr

niedz., 15 wrz 2019 o 15:47 Masataro Asai <notifications@github.com>
napisał(a):

**Comment by guicho271828** [comment]
> performance penalty for using double-floats

There are two misunderstandings:

+ first, yes, indeed double float computation is slower than single floats, it comsumes twice the Flops :)
+ second, the penalty I mentioned is the penalty of the dynamic dispatch based on the current value of `*numcl-default-float-format*`.

**Comment by PiotrWasik** [comment]
thanks :)

niedz., 15 wrz 2019 o 16:13 Masataro Asai <notifications@github.com>
napisał(a):
