### ISSUE TITLE
Small optimization.

### ISSUE THREAD

**Issue by commander-trashdin** [numcl/numcl#17]
Do you have rectangle matrices multiplication order optimization?

**Comment by guicho271828** [comment]
This? yes https://numcl.github.io/numcl/#performance

**Comment by guicho271828** [comment]
however not all functions are built on `einsum` currently, which is part of the plan.

**Comment by guicho271828** [comment]
While simple elementwise functions like `sin` are almost as fast as numpy, strided access etc. in `aref` is still using a naive implementation and thus very slow.

I incorpolated the strided loop extension into `einsum` in `einsum-refactor` branch. This makes it possible to reimplementing `aref` with `einsum`, which should make it significantly faster than the current implementation.

**Comment by commander-trashdin** [comment]
I am not sure it is the same thing. Lemme just make an example.

imagine I've got 3 matrices of sizes (50 5) (5 100) (100 10)
there are 2 ways to multiply then
(AB)C and A(BC)
first one gives `50*5*100 + 50*100*10 = 75000 `multiplications
second gives `5*100*10 + 50*5*10 = 7500`
tenfold difference.

It gets bigger when there are more matrices. However, it requires constant sizes at compile time....which is the case sometimes, I guess.

**Comment by guicho271828** [comment]
ok I understand what you mean. There are currently no cross-operation optimization like that at the moment.
I think [petalisp](https://github.com/marcoheisig/Petalisp) or tensorflow-like optimization can handle it well. That is also something I am thinking of...

**Comment by commander-trashdin** [comment]
I can make this.

**Comment by commander-trashdin** [comment]
If you are interested I can explain a simple idea I have for this optimization.
Maybe not here....but as you wish.

**Comment by commander-trashdin** [comment]
I mean there is a strict algorithm that produces the correct order in about O(n^3).

**Comment by guicho271828** [comment]
I think I understand what you mean now. You are specific about matmul, correct?

We need to perform 2 steps:
1. Make `matmul` take multiple arguments https://github.com/numcl/numcl/blob/master/src/4linear-algebra2.lisp#L48
2. Then implement that algorithm

Does it sound right?

**Comment by commander-trashdin** [comment]
Well:

1. You could also make a new function, which takes multiple arguments, instead of changing the old one.

2. I already kinda implemented it, wanna see?

**Comment by guicho271828** [comment]
plz submit a PR

**Comment by commander-trashdin** [comment]
Oof, not like this. However, I can make a gist with it as a single macro I made.

**Comment by commander-trashdin** [comment]
In fact, even like this.

https://github.com/thrashdin/fast-matrix

**Comment by guicho271828** [comment]
I have a question, does this work for arbitrary dimensional tensors?

**Comment by guicho271828** [comment]
in other words, tensordot rather than matmul

**Comment by commander-trashdin** [comment]
Not in a current state, no.

But my idea => this lib is easily extensible for tensors....I think.

Lemme think of an example an example.

**Comment by commander-trashdin** [comment]
Okay it is obviosly extensible.

But it's uneasy. Need to build a graph and do some dynamic programming. That....requires some better design I guess.

**Comment by commander-trashdin** [comment]
Thinking further, I actually consider this task interesting and I am willing to try it if:

1. You want to adopt this one.

2. You ll want to adopt it's upgrade for tensors if it succedds:)

**Comment by guicho271828** [comment]
I will check the code after the gym today

**Comment by commander-trashdin** [comment]
no pushing, just asking, how s it going?

Was very busy myself and will be for most of dec
but after that I really would like to help with various part, this included

**Comment by guicho271828** [comment]
exactly the same situation as you, hehe.. it turned out I was exhausted after the gym and couldnt keep awake. I appreciate your help on this.

more implementation idea: precompute the performance boundary for e.g. up to 5 arrays and insert the nested `if` forms that depends on the axis size.

re: you mentioned your code is based on macros, but it has to be implemented as functions + compiler-macro.

**Comment by guicho271828** [comment]
> exactly the same situation as you, hehe.. it turned out I was exhausted after the gym and couldnt keep awake. I appreciate your help on this.
and was of course busy in the daily life and work.

**Comment by guicho271828** [comment]
idea: in practical perspective, is DP better than a greedy approach?

**Comment by guicho271828** [comment]
I would like to see what numpy and jilua are doing.

**Comment by commander-trashdin** [comment]
what is dp?
Also, I updated my thing.
I just am not proficient enough to rework it into function + compiler macro
But it is in a somewhat working state.

**Comment by commander-trashdin** [comment]
Oh, got it.

Well, we'll need some serious tests, but I made 25 random sizes matrices and...it took 0.001 sec to reorder them right.

**Comment by commander-trashdin** [comment]
My macro outptus the some information, including speed gains.

**Comment by commander-trashdin** [comment]
A side question, soryy, but I cannot find `matrix_power` in this system.

Also, it doesn't load properly, with 
```
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "numcl" "src" "5where">
   [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]

; caught ERROR:
;   during macroexpansion of
;   (MATCH2*+ (ARRAY)
;       (T)
;     ...).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    The value
;      TRIVIA.LEVEL2.IMPL::_
;    is not of type
;      UNSIGNED-BYTE
; Debugger entered on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1006390823}>
```

**Comment by guicho271828** [comment]
> matrix_power in this system.

yes more matrix functions can be implemented.
Today I pushed some commits that includes a couple of dirty git history rewrites, so plz check if you have the current git HEAD.

**Comment by commander-trashdin** [comment]
From my perspective, last commit was 27 days ago.

Also, can we get some faster form of communication, rather then this issue? Not atm, but after 20 I am actually willing to help with many things, including documentation, as I am studying numpy/scipy atm and will be doing that for the rest of the year anyway. And also, this thing I made is better discussed in some other places. I use discord, but can get to IRC as well.

**Comment by guicho271828** [comment]
Which timezone are you in?

**Comment by commander-trashdin** [comment]
GMT+3

**Comment by commander-trashdin** [comment]
uhh, I digged into the source but cannot figure out this problem

```
; in: DEFUN WHERE
;     (TRIVIA.LEVEL2:EMATCH ARRAY
;       ((ARRAY :DISPLACED-TO NUMCL.IMPL::BASE :RANK NUMCL.IMPL::R)
;        (CHECK-TYPE NUMCL.IMPL::BASE ARRAY)
;        (NUMCL.IMPL::LOCALLY
;          (DECLARE (# NUMCL.IMPL::BASE))
;          (NUMCL.IMPL::LET (# # #)
;            (MAP-INTO NUMCL.IMPL::RESULT # NUMCL.IMPL::RESULT)
;            (REPLACE NUMCL.IMPL::TAILS2 NUMCL.IMPL::RESULT)
;            (ITERATE:ITER
;              #
;              #
;              #
;              #)
;            (COERCE NUMCL.IMPL::RESULT 'LIST)))))
; --> TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ 
; ==>
;   (TRIVIA.LEVEL2:MATCH2*+ (ARRAY)
;       (T)
;     (((ARRAY :DISPLACED-TO NUMCL.IMPL::BASE :RANK NUMCL.IMPL::R))
;      (CHECK-TYPE NUMCL.IMPL::BASE ARRAY)
;      (NUMCL.IMPL::LOCALLY
;        (DECLARE (# NUMCL.IMPL::BASE))
;        (NUMCL.IMPL::LET (# # #)
;          (MAP-INTO NUMCL.IMPL::RESULT # NUMCL.IMPL::RESULT)
;          (REPLACE NUMCL.IMPL::TAILS2 NUMCL.IMPL::RESULT)
;          (ITERATE:ITER
;            #
;            #
;            #
;            #)
;          (COERCE NUMCL.IMPL::RESULT 'LIST))))
;     ((#:OTHERWISE0)
;      (ERROR 'TRIVIA.LEVEL2:MATCH-ERROR :PATTERN '((# # #)) :VALUES
;             (LIST #:OTHERWISE0))))
; 
; caught ERROR:
;   during macroexpansion of
;   (MATCH2*+ (ARRAY)
;       (T)
;     ...).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    The value
;      TRIVIA.LEVEL2.IMPL::_
;    is not of type
;      UNSIGNED-BYTE

; in: DEFUN NONZERO
;     (NUMCL.EXPORTED:WHERE ARRAY
;      (LAMBDA (NUMCL.IMPL::X) (NOT (ZEROP NUMCL.IMPL::X))))
; --> BLOCK TRIVIA.LEVEL2:EMATCH TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ 
; ==>
;   (TRIVIA.LEVEL2:MATCH2*+ (ARRAY)
;       (T)
;     (((ARRAY :DISPLACED-TO NUMCL.IMPL::BASE :RANK NUMCL.IMPL::R))
;      (CHECK-TYPE NUMCL.IMPL::BASE ARRAY)
;      (NUMCL.IMPL::LOCALLY
;        (DECLARE (# NUMCL.IMPL::BASE))
;        (NUMCL.IMPL::LET (# # #)
;          (MAP-INTO NUMCL.IMPL::RESULT # NUMCL.IMPL::RESULT)
;          (REPLACE NUMCL.IMPL::TAILS2 NUMCL.IMPL::RESULT)
;          (ITERATE:ITER
;            #
;            #
;            #
;            #)
;          (COERCE NUMCL.IMPL::RESULT 'LIST))))
;     ((#:OTHERWISE0)
;      (ERROR 'TRIVIA.LEVEL2:MATCH-ERROR :PATTERN '((# # #)) :VALUES
;             (LIST #:OTHERWISE0))))
; 
; caught ERROR:
;   during macroexpansion of
;   (MATCH2*+ (ARRAY)
;       (T)
;     ...).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    The value
;      TRIVIA.LEVEL2.IMPL::_
;    is not of type
;      UNSIGNED-BYTE
; Debugger entered on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {100519C1C3}>
```

**Comment by commander-trashdin** [comment]
Reason why I tired in load numcl at all -- to check whether I can do it. Because as soon as I have some free time I m gonna write tests for my thing, and since I want the results to be relevant I'l be using your `matmul` function (instead of some simple one I could craft myself). Same goes for `tensordot`.

**Comment by guicho271828** [comment]
Oh, I didn't realise you had a build problem.
Did you pull the latest HEAD from the github?
Did you also pull from all numcl-specific dependencies outside quicklisp ? (specialized-function, etc)
Is trivia and all other dependencies inside quicklisp up-to-date by `quicklisp:upgrade-all-dist` ?
If you haven't, please do.

**Comment by guicho271828** [comment]
btw, I am in GMT-5, Boston.

**Comment by guicho271828** [comment]
and you must be a night owl.

**Comment by guicho271828** [comment]
Relatively recent SBCL is also recommended. At least later than 1.5.0

**Comment by commander-trashdin** [comment]
Oh, probably should refresh non ql stuff, too. I also have bleeding edge fresh sbcl as well as all ql related stuff. As well as mostly everything on my system).

And yes, I am desperately trying to fix my sleep schedule, as I am studying and working hard until 20 Dec, and staying late at night is _not_ helping.

**Comment by guicho271828** [comment]
so far, loading numcl as well as testing it (run it via `(asdf:test-system :numcl)`) runs without problem both on my PC (SBCL 1.5.9) as well as on Travis.

**Comment by commander-trashdin** [comment]
Okay, I will try it tomorrow, after updating all side systems.

**Comment by commander-trashdin** [comment]
nope, didn't seem to help.
When I try to quickload it (after putting everything into local-projects) it gives me the same type error

When I try to asdf load it it gives me the `:FIVEAM not found, required by #<SYSTEM "numcl.test">`

**Comment by commander-trashdin** [comment]
`gtype`, `constantfold`, `specialized-function` and `trivia` all load correctly, but then this type error happens, and I cannot seem to find it. This is really weird.

**Comment by guicho271828** [comment]
you need to do `(ql:quickload :numcl.test)` before testing then...

**Comment by guicho271828** [comment]
show me the HEAD md5 of numcl. which branch are you on? `master` or `einsum-refactor`? ALL details matter.

**Comment by commander-trashdin** [comment]
I literally just downloaded the source from here and put it into local-projects.

**Comment by guicho271828** [comment]
Please compose the precise words that has no ambiguity, and anticipate how the words could be interpreted by the third person.

* Does "bleeding edge fresh sbcl" mean a developmental HEAD of SBCL? Please no, use the release versions like 1.5.x . Show the result of `(lisp-implementation-version)` too.
* Which version of Trivia is it? quicklisp? Have you ever cloned a separate Trivia repo in local-project? Even if you are confident that it is from quicklisp, confirm it by `(ql:where-is-system :trivia)`.
* People usually do not refer to `git clone`-ing a repo as `download`. Did you download the source code as a zip or tar file from the releases? Then please no, that one is too old and has an unfixed bug. Just clone the fresh master in `local-project` by `git clone https://github.com/numcl/numcl.git`. You need to then run `(ql:register-local-projects)` and finally `(ql:quickload :numcl)`.
* Are you on either Mac or Linux?

**Comment by commander-trashdin** [comment]
okay, lemme say it differently
This is sbcl 1.5.9

Trivia is from quicklisp, which I have checked.

Yeah, I am....not really confident with my git skills, so I downloaded a zip. Will clone it, alright.

Debian 10.

**Comment by commander-trashdin** [comment]
Oh, wait, I'm sorry I think I found the problem.

I had 2 trivias -- one from ql and one from local-projects.
And they kinda mixed into each other in a weird way. I removed the wrong one and it all works now, thanks a lot.

Now I can get to proper testing.

**Comment by commander-trashdin** [comment]
Too tired to write proper tests, but quick comparison shows something along the lines of
```
Evaluation took:
  0.435 seconds of real time
  0.438365 seconds of total run time (0.425913 user, 0.012452 system)
  [ Run times consist of 0.065 seconds GC time, and 0.374 seconds non-GC time. ]
  100.69% CPU
  38 forms interpreted
  2,596 lambdas converted
  1,220,355,492 processor cycles
  492,434,992 bytes consed


The resulting matrix dimensions: (43 31)
Required atomic multiplications: 647729
Compared to: 2005434 multiplications in naive implementation
Acceleration ratio is 3.0961003
Evaluation took:
  0.082 seconds of real time
  0.082526 seconds of total run time (0.082526 user, 0.000000 system)
  [ Run times consist of 0.007 seconds GC time, and 0.076 seconds non-GC time. ]
  101.22% CPU
  229,874,681 processor cycles
  91,016,192 bytes consed
```

**Comment by commander-trashdin** [comment]
When run with 
```
(progn
  (sb-ext:gc :full t)
  (time
   (loop :repeat 10
         :do (foo))))
```

shows

```
Evaluation took:
  2.938 seconds of real time
  2.974445 seconds of total run time (2.914589 user, 0.059856 system)
  [ Run times consist of 0.251 seconds GC time, and 2.724 seconds non-GC time. ]
  101.23% CPU
  8,248,968,819 processor cycles
  4,598,980,128 bytes consed
  
The resulting matrix dimensions: (43 31)
Required atomic multiplications: 647729
Compared to: 2005434 multiplications in naive implementation
Acceleration ratio is 3.0961003
Evaluation took:
  0.615 seconds of real time
  0.621872 seconds of total run time (0.584584 user, 0.037288 system)
  [ Run times consist of 0.052 seconds GC time, and 0.570 seconds non-GC time. ]
  101.14% CPU
  1,726,515,207 processor cycles
  909,641,840 bytes consed
```

Conclusion -- seems worth developing further, at least.

**Comment by commander-trashdin** [comment]
Oh, and, btw, not like I am inventing this, and also not like I am inventing it in the most efficient way.

https://en.wikipedia.org/wiki/Matrix_chain_multiplication

**Comment by guicho271828** [comment]
yes i know.

**Comment by guicho271828** [comment]
If you are deeply interested in the similar topic as a research, then I would suggest looking into the numpy source code especially the C++ side.

**Comment by commander-trashdin** [comment]
I started thinking about...
Can that fast solution be extended to tensors... building something n-dimensional and non-convex, and dividing it into simplexes..
Very much not sure, will think about it later.

**Comment by guicho271828** [comment]
The first most easy solution to the problem may be to formulate it as a linear programming problem and then put it into the lp solver and solve it.

**Comment by guicho271828** [comment]
then you could think about the more specialized solution

**Comment by commander-trashdin** [comment]
I realized that my lisp-fu is too weak atm to make a proper function/compiler macro pair for this.
I am going to work on it, but in the meantime, everything else I wrote works and the speedup is decent, so you (and anybody else) can use it already. 

I am reading the article from wiki where they explain how to do this in nlogn time. Wanna dig a bit into it.

**Comment by guicho271828** [comment]
If you are not confident in git skills, I would suggest forking numcl on github, clone your fork in local-project (remove the old one), copy all files in a subdirectory of numcl, commit everything with `git commit --signoff` option (see below), push it, and send me a pull request.

(`--signoff` in this repo implies that you certify that you are the author of the code, and you did not stole someone else's code. See `legal/DCO1.1.txt`. This is required in this project for the IP standpoint (my company cares) and this is also a practice done in the Linux kernel code. Honestly this is the first time I was required to let the contributers add it.)

       -s, --signoff
           Add Signed-off-by line by the committer at the end of the commit
           log message. The meaning of a signoff depends on the project, but
           it typically certifies that committer has the rights to submit this
           work under the same license and agrees to a Developer Certificate
           of Origin (see http://developercertificate.org/ for more
           information).

**Comment by guicho271828** [comment]
This way I can keep crediting you and modify your implementation the right way. You will see the result to learn how to do it.
