### ISSUE TITLE
Adding two matrices together

### ISSUE THREAD

**Issue by davd33** [numcl/numcl#22]
Hello, thank you for this awesome project!

I was failing to find a way to add two matrices together like in pynum.
Can you please tell me how I would do that, if possible?

**Comment by guicho271828** [comment]
It takes the normal common lisp arrays, but it does not take arbitrary arrays. Use `asarray` to your array.
See
https://github.com/numcl/numcl#quick-tutorial

**Comment by guicho271828** [comment]
`asarray` documentation
https://numcl.github.io/numcl/#defun-asarray-contents-&key-type

**Comment by davd33** [comment]
It works :) Thank you
