### ISSUE TITLE
Suggested improvement to 1version.lisp

### ISSUE THREAD

**Issue by mirkov** [numcl/numcl#28]
Loading numcl on Windows10+CCL failed on 1version.lisp at the 
`(uiop:run-program
                    (format nil "cd ~a ; git rev-parse HEAD"
                            (asdf:system-source-directory :numcl))
                    :output '(:string :stripped t))`

I fixed it by replacing the semi-colon with the double ampersand like so
`(uiop:run-program
                    (format nil "cd ~a && git rev-parse HEAD"
                            (asdf:system-source-directory :numcl))
                    :output '(:string :stripped t))`

I do not understand why `;` was failing.  Possibly the `c:/Users/...` was causing the problem. 

I am submitting this as an FYI - I am not using numcl at the moment, so this is not a show stopper.

**Comment by guicho271828** [comment]
Is it probably because your username contain a space? Does adding extra \"\" around ~a also fix the issue?

**Comment by mirkov** [comment]
Apology for not writing sooner - I just noticed the reply.

To reply: my username does not contain spaces. In general I avoid spaces in Windows pathnames.

After many months, and now on a new laptop, I cannot reproduce this problem. (I still cannot load numcl, but that is likely because of some other, non-numcl and non-lisp, issues).

**Comment by mirkov** [comment]
On a new Windows laptop, I cannot reproduce this problem. 

I still cannot load numcl, but that is likely because of some other, non-numcl and non-lisp, issues.
