### ISSUE TITLE
Bug: aref with negative indices

### ISSUE THREAD

**Issue by digikar99** [numcl/numcl#30]
As I understand, the current semantics for aref are that the subscript can either be 
- a s-expression evaluating to a valid index
- a list of two elements: `(a b) ;=> a:b`
- a list of three elements: `(a b c) ;=> a:b:c`
with `t` being equivalent to an absence of argument.

However, there seem to be a few examples that work in numpy but not yet in numcl include (or work incorrectly):

```lisp
(defparameter a (asarray '((1 2 3) (4 5 6))))
(aref a '(t -1)) ;=> #2A((1 2 3) (4 5 6)) ; a[:-1] in numpy returns array[[1,2,3]]
(aref a t '(t -1)) ;=> #2A((1 2 3) (4 5 6)) ; a[:, :-1] in numpy returns array([[1, 2], [4, 5]])
;;; Though
(numcl:aref a t '(t -2)) ;=> #2A((1 2) (4 5)) ; seems to be an off by one error - or is it as expected?
```

**Comment by guicho271828** [comment]
I might have had a wrong understanding of the semantics of the negative index.
ok, so -1 denotes the last element when used for indexing, but not when used in a range...

I am mildly angry about it but I will stick to the principle (following numpy).
Thank you for reporting this.

**Comment by guicho271828** [comment]
See new tests in 
https://github.com/numcl/numcl/commit/22371894592c495993bb9678b97f253401685697#diff-1fe014c27f109bcc96ecb5121ed6d3eeR505
and
https://github.com/numcl/numcl/commit/ea5809a8b46864f8962d21fdccd88725ae218f40#diff-1fe014c27f109bcc96ecb5121ed6d3eeR142-R147
