### ISSUE TITLE
Option to turn off optimization: compile-speed matters

### ISSUE THREAD

**Issue by digikar99** [numcl/numcl#31]
While working in slime, and using small data and examples (or even large!), I don't think run-time for very large arrays is anything of concern; rather compile-time feels like a big concern. For example, check the difference in the compile times of:

```lisp
(defun foo (a b) (- a b))
(defun foo (a b) (numcl:- a b))
```

The second takes significantly longer to compile. And it would be great if an option is included to turn off such optimization. I don't want this to be the julia's time to first plot issue!

Thanks!

**Comment by guicho271828** [comment]
yes the specialized code is compiled on the first run, assuming it will run faster on the later runs.
In a more involved use case, I believe unlike julia, you could dump an image that contains the compiled specialized code stored in memory.
So far I do not have a good alternative approach to this issue.

**Comment by digikar99** [comment]
So, I'm playing with it a bit; the issue can be avoided to some extent by `(declaim (notinline numcl:-))` - this avoids the "complete" recompilation. It does still take time for the first call to `numcl:-` but the functions that build over it are recompiled at the "usual speed" of normal functions.

Is there (I'd guess there has to be! What is? :D) a way to access compiler declarations? 

Say, something like when declaimed to optimized for speed, one could turn on inline optimization; while at other times, or when optimized for debug, turn it off; or some variable to control it.

Edit: `(declaim (notinline numcl.impl::%coerce numcl:-))` seems good enough!

**Comment by digikar99** [comment]
This works great too!

```lisp
(declaim (optimize (compilation-speed 3)))
```

<3 Common Lisp!

**Comment by digikar99** [comment]
Should this issue be closed? (And may be reopened if someone is not satisfied with this solution.)

**Comment by guicho271828** [comment]
yes, thanks.
