### ISSUE TITLE
Semantics for some functions do not match with CL exactly

### ISSUE THREAD

**Issue by digikar99** [numcl/numcl#35]
For instance, `(numcl:+)` raises an invalid number of arguments error, while `(cl:+)` happily evaluates to 0. Is that intended or is this a bug?

This seems to be readily remedied by adding an `:initial-value` argument, changing 

```lisp
(defun numcl:+   (&rest args) (reduce (lambda (x y) (broadcast '+ x y)) args))
```

to

```lisp
(defun numcl:+   (&rest args) (reduce (lambda (x y) (broadcast '+ x y)) args :initial-value 0))
```

**Comment by guicho271828** [comment]
fixed for `+` and `*`. What else?
