### ISSUE TITLE
WARNING: Missing type inference function for 1+, defaults to T

### ISSUE THREAD

**Issue by stefandevai** [numcl/numcl#37]
Hello!

I'm having this warning when using `map-array`:

```lisp
(numcl:map-array 'cl:1+ (numcl:asarray '(2 2)))
;; WARNING: Missing type inference function for 1+, defaults to T
;; => #(3 3)
```
I don't understand how I can implement an inference function. I read the docs and the source, but I couldn't find anything related to that.

**Comment by guicho271828** [comment]
I see, I agree that I need a documentation for hacking the internal.
For a starter, open `2typeinfer.lisp`, then try below
```
(set-type-inferer
 '1+
 (defun 1+-inferer (typespec)
   (interpret-type `(+ 1 ,typespec)))
```

Note, I have a inferer bug related to positive and negative infinity, and working on it. Interface to `interpret-type` will not change, so more additions are appreciated. Thanks!

**Comment by guicho271828** [comment]
#38

**Comment by guicho271828** [comment]
Done.
