### ISSUE TITLE
Cleaner-syntax: using (&rest arrays-key1-key2) instead of (arrays &key key1 key2)

### ISSUE THREAD

**Issue by digikar99** [numcl/numcl#39]
I think the former syntax makes for a cleaner code. Albeit, this does demand significant API changes.

PS: Let me know if this is good; this seems doable for someone not very familiar with the numcl internals.

**Comment by guicho271828** [comment]
Explain your idea more clearly.

**Comment by digikar99** [comment]
Basically doing the argument list destructuring inside the function using destructuring-bind and a helper function, instead of at the function boundary, so that it is possible to write `(zeros 3 4 :type 'single-float)` instead of requiring `shape` to be a list `(zeros '(3 4) :type 'single-float)`.

About the API changes, perhaps, this can be done without API changes by allowing both syntaxes. I don't see an ambiguity arise - does it arise?

**Comment by guicho271828** [comment]
I don't like the idea. I especially don't like the API change for API change's sake.

**Comment by digikar99** [comment]
That's fine! The proposed API doesn't play well with `apply` as well.
