### ISSUE TITLE
numcl:/ Control stack exhausted.

### ISSUE THREAD

**Issue by hyotang666** [numcl/numcl#42]
* (lisp-implementation-type)

"SBCL"
* (lisp-implementation-version)

"2.0.2"
* (numcl:numcl-version)

"numcl-20200427-git"
* (numcl:/ (numcl:asarray '(1.0 2.0 3.0)) (numcl:asarray '(2.0 4.0 6.0)))
Control stack guard page temporarily disabled: proceed with caution

debugger invoked on a SB-KERNEL::CONTROL-STACK-EXHAUSTED in thread
#<THREAD "main thread" RUNNING {1000518083}>:
  Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.

* (dribble)

Should I specify heap size?

**Comment by guicho271828** [comment]
Doesnt reproduce in SBCL 2.0.5. dynamic space size is 8G.
```
; SLIME 2.24To load "numcl":
  Load 1 ASDF system:
    numcl
; Loading "numcl"
.
Switching to the BALLAND2006 optimizer
...

CL-USER> (numcl:/ (numcl:asarray '(1.0 2.0 3.0)) (numcl:asarray '(2.0 4.0 6.0)))
#(0.5 0.5 0.5)
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> (lisp-implementation-version)
"2.0.5"
CL-USER> (dynamic-space-size)
8388608000
CL-USER> 
```

**Comment by guicho271828** [comment]
Same with 2.0.2.
```
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> (lisp-implementation-version)
"2.0.2"
To load "numcl":
  Load 1 ASDF system:
    numcl
; Loading "numcl"
.
Switching to the BALLAND2006 optimizer
...

CL-USER> (numcl:/ (numcl:asarray '(1.0 2.0 3.0)) (numcl:asarray '(2.0 4.0 6.0)))
#(0.5 0.5 0.5)
CL-USER> 
```

**Comment by guicho271828** [comment]
oops, my local copy was not up-to-date.

**Comment by guicho271828** [comment]
Reproduced in 2.0.2 .

**Comment by guicho271828** [comment]
The issue is due to the error in type inference. `(/ (single-float * *) (single-float * *))` should return `(single-float * *)`, but it returns NIL, and `specialized-function` does not support element-type `NIL`.

**Comment by guicho271828** [comment]
fix commited, closed.
