### ISSUE TITLE
example.lisp crashes

### ISSUE THREAD

**Issue by kolloid** [numcl/numcl#47]
Hi
After installing numcl in sbcl 2.0.5 running on Linux Mint (ubunt-ish), I attempted to run example.lisp which after considerable
work crashed with a diagnostic error:

**Compile-time error:
  during macroexpansion of
(NUMCL.IMPL::LET (#)
  (DECLARE #)
  ...).
 The value
   SYMBOL
 is not of type
   (TYPE-R:ARRAY-SUBTYPE TYPE-R::ELEMENT-TYPE TYPE-R::DIMENSIONS)**

My sbcl has 6Gb of dynamic memory.

Tom

**Comment by guicho271828** [comment]
sorry that example.lisp was rather left untouched for a while.
fixed in d19f363
