### ISSUE TITLE
linspace output from numcl is different to numpy

### ISSUE THREAD

**Issue by benzwick** [numcl/numcl#49]
In numcl I get the following output from `linspace`:
```
(linspace 2.0 3.0 5)
#(2.0 2.2 2.4 2.6000001 2.8000002)
(linspace 2.0 3.0 5 :endpoint t)
#(2.0 2.1666667 2.3333335 2.5000002 2.666667 2.8333337)
```
which does not include the endpoints, whereas in numpy I get (note that `endpoint=True` is the default):
```
np.linspace(2.0, 3.0, 5)
array([2.  , 2.25, 2.5 , 2.75, 3.  ])
np.linspace(2.0, 3.0, 5, endpoint=True)
array([2.  , 2.25, 2.5 , 2.75, 3.  ])
```
Is this a bug in numcl?

The [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) suggests using `linspace` instead of `arange` to ensure that endpoints are included but numcl uses `arange` inside the `linspace` function:
https://github.com/numcl/numcl/blob/9ca804aac3ce7d3c6f7fbcb4626ee0b4bfc3265e/src/3arange.lisp#L250-L251
so there does not appear to be any benefit of using `linspace` over `arange` in numcl.

**Comment by guicho271828** [comment]
these convenient functions are pretty much untested.
I focused mostly on the backend development and simple functions and dont have time to test those.
Appreciated if you can.

**Comment by benzwick** [comment]
Would this be a suitable replacement `linspace` function:
```
(defun linspace (start stop &key (num 50) (endpoint t) retstep type)
  (declare (fixnum num))
  (declare ((or integer ratio single-float double-float) start stop))
  (let* ((start (if type (coerce start type) start))
         (stop  (if type (coerce stop  type) stop))
         (step (/ (- stop start) (1- num)))
         (lst (loop for i from 0 below (1- num)
                    for x from start by step
                    collect x))
         (lst (if endpoint (append lst (list stop)) lst))
         (arr (make-array (if endpoint num (1- num))
                          :initial-contents lst)))
    (if retstep (list arr step) arr)))
```
It gives the following output:
```
* (linspace 2 3 :num 5)
#(2 9/4 5/2 11/4 3)

* (linspace 2.0 3.0 :num 5)
#(2.0 2.25 2.5 2.75 3.0)

* (linspace 2d0 3d0 :num 5)
#(2.0d0 2.25d0 2.5d0 2.75d0 3.0d0)

* (linspace 2 3 :num 5 :type 'single-float)
#(2.0 2.25 2.5 2.75 3.0)

* (linspace 2 3 :num 5 :type 'double-float)
#(2.0d0 2.25d0 2.5d0 2.75d0 3.0d0)

* (linspace 2 3 :num 5 :endpoint nil :type 'double-float :retstep t)
(#(2.0d0 2.25d0 2.5d0 2.75d0) 0.25d0)
```

The NumPy function arguments are as follows:
```
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0):
```

References can be found here:
- NumPy: https://github.com/numpy/numpy/blob/v1.19.0/numpy/core/function_base.py#L23-L165
- Matlab: https://www.mathworks.com/help/matlab/ref/linspace.html

> these convenient functions are pretty much untested.
> I focused mostly on the backend development and simple functions and dont have time to test those.
> Appreciated if you can.

I'm quite new to common lisp so it might take me some time to get familiar with writing proper tests. Do you mean by adding them to this file: <https://github.com/numcl/numcl/blob/master/t/package.lisp>?

**Comment by guicho271828** [comment]
Thank you very much for the code.
re:Test, yes, that is appreciated.

**Comment by guicho271828** [comment]
> (defun linspace (start stop &key (num 50) (endpoint t) retstep type)
>   (declare (fixnum num))
>   (declare ((or integer ratio single-float double-float) start stop))

I believe you intended to use `real`,

> (defun linspace (start stop &key (num 50) (endpoint t) retstep type)
>   (declare (fixnum num))
>   (declare (real start stop))

 but does it need to be real? I guess just `number` works (which includes `complex`):

> (defun linspace (start stop &key (num 50) (endpoint t) retstep type)
>   (declare (fixnum num))
>   (declare (number start stop))

**Comment by guicho271828** [comment]
`retstep` would not make much sense in common lisp. I would suggest just always returning multiple values `(values arr step)` instead of switching single value and a list. Lisp's multiple values are on stack and does not need consing, unlike python's tuples.

**Comment by guicho271828** [comment]
`make-array` returns a normal array, which does not satisfy `numcl`'s assumption. https://github.com/numcl/numcl#quick-tutorial
this must be fixed.

**Comment by benzwick** [comment]
Thanks for the feedback @guicho271828. I made the changes you suggested and created a new pull request. Please let me know if there is anything else I can do to improve the code.
