### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [numcl/numcl#59]
Building with SBCL 2.1.10 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id b4cdb25eb843cdea7a7be3b2a4e9e62e61ef5037

*numcl.test* fails to build because of a failure in  _numcl_.

*numcl* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as a type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C08103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "numcl" "src" "1type">

```

[Full log here](http://report.quicklisp.org/2021-11-02/failure-report/numcl.html)

**Comment by xach** [comment]
Any word on this? I will have to drop numcl from quicklisp if it is not addressed sometime.

**Comment by guicho271828** [comment]
Ah sorry I should work on this tonight

**Comment by guicho271828** [comment]
fixed locally
