### ISSUE TITLE
vander function error

### ISSUE THREAD

**Issue by anranyicheng** [numcl/numcl#60]
Hi, in the file example.lisp 
(vander (asarray #(1 2 3 5) :n) 3) 
result is error.
then I enter:
(vander (asarray #(1 2 3 5))) 
the error is :
The value
  27
is not of type
  (UNSIGNED-BYTE 4)
when setting an element of (ARRAY (UNSIGNED-BYTE 4))
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1001514103}>)

Backtrace:
  0: ((SB-VM::OPTIMIZED-DATA-VECTOR-SET (UNSIGNED-BYTE 4)) #<unavailable argument> #<unavailable argument> #<unavailable argument>)
  1: (VANDER #(1 2 3 5) :N NIL :INCREASING NIL)
  2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (VANDER (ASARRAY #(1 2 3 5))) #<NULL-LEXENV>)
  3: (EVAL (VANDER (ASARRAY #(1 2 3 5))))
 --more--

**Comment by guicho271828** [comment]
noted.

**Comment by guicho271828** [comment]
is this fixed??

**Comment by guicho271828** [comment]
(magically?)

**Comment by anranyicheng** [comment]
Hi,  
This bug occurs because assarry defult type is UNSIGNED-BYTE, for the vander function,  type should be  'fixnum.
(vander (asarray '(1 2 3 5) :type 'fixnum ))

**Comment by guicho271828** [comment]
I see.
As with other functions, ideally numcl must look at the input and deduce the specialized array type with the smallest bitwidth based on the operation it performs. Vandermonde matrix uses a exponential function. Therefore it should first compute [maximum element] ^ [length of vector] then decide the type.
